/* IMPORTAR DADOS DE OUTRA TABELA */

/* PARA IMPORTAR REGISTROS DE UMA TABELA PARA OUTRA, DEVEMOS TER OS CAMPOS COM OS MESMOS NOMES E TIPOS DE DADOS */

SELECT CODIGO_DO_PRODUTO, NOME_DO_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA
FROM sucos_vendas.tabela_de_produtos WHERE CODIGO_DO_PRODUTO LIKE '%104%' ORDER BY CODIGO_DO_PRODUTO DESC;

/* PARA A TABELA tabela_de_produtos DO BANCO sucos_vendas TEREM OS MESMOS CAMPOS QUE A TABELA produtos DO BANCO vendas_sucos,
	devemos usar ALIAS (AS)*/

SELECT CODIGO_DO_PRODUTO AS CODIGO,
NOME_DO_PRODUTO AS DESCRITOR,
EMBALAGEM,
TAMANHO,
SABOR,
PRECO_DE_LISTA AS PRECO_LISTA
FROM sucos_vendas.tabela_de_produtos;

/* PARA EVITAR QUE PRODUTOS SE REPITAM, ADICIONE UMA CONDIÇÃO */
SELECT CODIGO_DO_PRODUTO AS CODIGO,
NOME_DO_PRODUTO AS DESCRITOR,
EMBALAGEM,
TAMANHO,
SABOR,
PRECO_DE_LISTA AS PRECO_LISTA
FROM sucos_vendas.tabela_de_produtos
WHERE CODIGO_DO_PRODUTO NOT IN (SELECT CODIGO FROM PRODUTOS);

/* AGORA BASTA INSERIR NA TABELA DESEJADA, RESPEITANDO A ORDEM DOS CAMPOS */
INSERT INTO PRODUTOS(CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
SELECT CODIGO_DO_PRODUTO AS CODIGO,
NOME_DO_PRODUTO AS DESCRITOR,
SABOR,
TAMANHO,
EMBALAGEM,
PRECO_DE_LISTA AS PRECO_LISTA
FROM sucos_vendas.tabela_de_produtos
WHERE CODIGO_DO_PRODUTO NOT IN (SELECT CODIGO FROM PRODUTOS);

SELECT * FROM PRODUTOS WHERE CODIGO LIKE '%104%' ORDER BY CODIGO DESC;
SELECT CODIGO_DO_PRODUTO, NOME_DO_PRODUTO, EMBALAGEM, TAMANHO, SABOR, PRECO_DE_LISTA
FROM sucos_vendas.tabela_de_produtos WHERE CODIGO_DO_PRODUTO LIKE '%104%' ORDER BY CODIGO_DO_PRODUTO DESC;

/* segundo exemplo */

SELECT CPF, NOME, ENDERECO_1 AS ENDERECO,
BAIRRO, CIDADE, ESTADO, CEP,
DATA_DE_NASCIMENTO AS DATA_NASCIMENTO, IDADE, SEXO,
LIMITE_DE_CREDITO AS LIMITE_CREDITO,
VOLUME_DE_COMPRA AS VOLUME_CREDITO,
PRIMEIRA_COMPRA FROM sucos_vendas.tabela_de_clientes;

SELECT * FROM vendas_suco.clientes;

INSERT INTO vendas_suco.CLIENTES(CPF, NOME, ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_NASCIMENTO, IDADE, SEXO,
LIMITE_CREDITO, VOLUME_CREDITO, PRIMEIRA_COMPRA)
SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,
IDADE, SEXO, LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA AS VOLUME_CREDITO, PRIMEIRA_COMPRA
FROM sucos_vendas.tabela_de_clientes
WHERE CPF NOT IN (SELECT CPF FROM vendas_suco.CLIENTES);

