/* INSERIR VALORES EM UMA TABELA */

USE vendas_suco;

INSERT INTO PRODUTOS(CODIGO, DESCRITOR, SABOR, TAMANHO, EMBALAGEM, PRECO_LISTA)
VALUES('1040107', 'Light - 350ml - Melancia', 'Melancia', '350ml', 'Lata', 4.56);

SELECT * FROM PRODUTOS;