/* AUTO_INCREMENT */
/* o campo que tiver AUTO_INCREMENT deve ser SEMPRE CHAVE PRIMÁRIA */

CREATE TABLE TABELA_IDENTIDADE (
	ID INT AUTO_INCREMENT,
    DESCRITOR VARCHAR(50),
    PRIMARY KEY (ID)
);

INSERT INTO TABELA_IDENTIDADE (DESCRITOR) VALUES ('CLIENTE 1');
INSERT INTO TABELA_IDENTIDADE (DESCRITOR) VALUES ('CLIENTE 2');
INSERT INTO TABELA_IDENTIDADE (DESCRITOR) VALUES ('CLIENTE 3');
INSERT INTO TABELA_IDENTIDADE (DESCRITOR) VALUES ('CLIENTE 4');
INSERT INTO TABELA_IDENTIDADE (DESCRITOR) VALUES ('CLIENTE 5');
DELETE FROM tabela_identidade WHERE DESCRITOR = 'CLIENTE 1';

SELECT * FROM TABELA_IDENTIDADE;

INSERT INTO TABELA_IDENTIDADE (ID, DESCRITOR) VALUES (NULL, 'CLIENTE 6');	/* vai continuar com a contagem de onde parou*/
INSERT INTO TABELA_IDENTIDADE (DESCRITOR) VALUES ('CLIENTE 7');
INSERT INTO TABELA_IDENTIDADE (DESCRITOR) VALUES ('CLIENTE 8');

SELECT * FROM TABELA_IDENTIDADE;

INSERT INTO TABELA_IDENTIDADE (ID, DESCRITOR) VALUES (100, 'CLIENTE 9');	/* pula para o número 100 e os próximos registros adicionados serão contados a partir desse*/
INSERT INTO TABELA_IDENTIDADE (DESCRITOR) VALUES ('CLIENTE 10');
INSERT INTO TABELA_IDENTIDADE (DESCRITOR) VALUES ('CLIENTE 11');

SELECT * FROM TABELA_IDENTIDADE;

/* PERCEBA que ele retrocedeu a contagem da linha 25, porém, os próximos
registros que não tiverem especificação do ID serão automaticamente incrementados pela contagem do maior ID */
INSERT INTO TABELA_IDENTIDADE (ID, DESCRITOR) VALUES (9, 'CLIENTE 12');	
INSERT INTO TABELA_IDENTIDADE (DESCRITOR) VALUES ('CLIENTE 13');	/* como não foi especificado o ID, o ID desse registro será 103 */

SELECT * FROM TABELA_IDENTIDADE;
