/* FUNÇÕES MATEMÁTICAS */

/*ROUND - SQRT -   */

SELECT (20 + (40 - 13)/13) AS RESULTADO;
SELECT CEILING(42.4454532345) AS RESULTADO;
SELECT ROUND(563.909999999324) AS RESULTADO;
SELECT ROUND(563.42323299999) AS RESULTADO;
SELECT FLOOR(42.4454532345) AS RESULTADO;

SELECT RAND() AS RESULTADO;

SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE * PRECO, 2) AS FATURAMENTO FROM itens_notas_fiscais;

/*Na tabela de notas fiscais temos o valor do imposto. Já na tabela de itens temos
 a quantidade e o faturamento. Calcule o valor do imposto pago no ano de 2016 arredondando para o menor inteiro.*/

SELECT YEAR(DATA_VENDA) AS `ANO`, FLOOR(SUM((QUANTIDADE * PRECO) * IMPOSTO)) AS `IMPOSTO PAGO`
FROM notas_fiscais A
INNER JOIN itens_notas_fiscais B
ON A.NUMERO = B.NUMERO AND YEAR(DATA_VENDA) = 2016;

/* SUM, MAX, MIN, AVG, COUNT / GROUP BY */

SELECT BAIRRO, VOLUME_DE_COMPRA FROM tabela_de_clientes;
SELECT BAIRRO, SUM(VOLUME_DE_COMPRA) AS TOTAL_VOLUME_DE_COMPRA FROM tabela_de_clientes GROUP BY BAIRRO;
SELECT ESTADO, SUM(LIMITE_DE_CREDITO) AS 'TOTAL LIMITE DE CRÉDITO' FROM tabela_de_clientes GROUP BY ESTADO;

SELECT * FROM itens_notas_fiscais ORDER BY PRECO;
SELECT COUNT(*) FROM itens_notas_fiscais; /*Conta o total de registros*/
SELECT CODIGO_DO_PRODUTO, COUNT(*) AS TOTAL_DE_REGISTROS FROM itens_notas_fiscais GROUP BY CODIGO_DO_PRODUTO;

SELECT CODIGO_DO_PRODUTO, COUNT(QUANTIDADE) AS QUANTIDADE_TOTAL FROM itens_notas_fiscais
WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99 GROUP BY CODIGO_DO_PRODUTO;
