/* FUNÇÕES DE DATA */

SELECT DATE_ADD("2019-03-19", INTERVAL 4 MONTH) AS RESULTADO;
SELECT ADDDATE("2018-10-28", INTERVAL 10 DAY) AS RESULTADO;
SELECT ADDDATE("2015-02-10", INTERVAL 2 YEAR) AS RESULTADO;

SELECT DATE_SUB("2019-03-19", INTERVAL 20 DAY) AS RESULTADO;

SELECT CURDATE();		/* traz a data atual */
SELECT CURRENT_DATE();	/* traz a data atual */
SELECT CURRENT_TIME();	/* traz a hora atual */
SELECT CURRENT_TIMESTAMP();	/* traz a data e as horas atuais */

SELECT DATEDIFF("2014-09-20","2014-09-24");		/* -4  */
SELECT DATEDIFF("2014-09-24", "2014-09-20"); 	/*  4  */

SELECT DAYNAME("2014-09-24");	/* Wednesday */
SELECT MONTHNAME("2014-09-24");	/* September */

/* Crie uma consulta que mostre o nome e a idade atual dos clientes. */
SELECT NOME, DATA_DE_NASCIMENTO, CURRENT_DATE() AS `DATA ATUAL` FROM tabela_de_clientes;
SELECT NOME, DATA_DE_NASCIMENTO, TIMESTAMPDIFF(YEAR, DATA_DE_NASCIMENTO, CURRENT_DATE()) AS IDADE FROM tabela_de_clientes;
SELECT NOME, DATA_DE_NASCIMENTO, CONCAT(TIMESTAMPDIFF(YEAR, DATA_DE_NASCIMENTO, CURRENT_DATE()), " ANOS") AS IDADE FROM tabela_de_clientes;	/* testando combinação com funções de strings */



