/* TRIGGER */
/* SEM USAR STORED PROCEDURES PARA FINS DIDÁTICOS */
/* EXEMPLOS DE TRIGGERS COM UPDATE, INSERT E DELETE */

USE TESTES_TRIGGERS;
CREATE DATABASE IF NOT EXISTS TESTES_TRIGGERS;

/* CRIAR TABELA FATURAMENTO: TRIGGER CALCULA AUTOMATICAMENTE O VALOR TOTAL DAS VENDAS */
CREATE TABLE TABELA_FATURAMENTO
(DATA_VENDA DATE NULL,
TOTAL_VENDA FLOAT);

CREATE TABLE ITENS_NOTAS
(NUMERO INT,
DATA_VENDA DATE NULL,
VENDA FLOAT)

CREATE TABLE TABELA_CLIENTES
(NOME VARCHAR(50),
DATA_NASCIMENTO DATE,
IDADE INT
)

/* AFTER = Executa depois do comando (INSERT, DELETE, UPDATE, etc)
   BEFORE = Executa antes do comando (INSERT, DELETE, UPDATE, etc)*/

DELIMITER //
CREATE TRIGGER TG_CALCULO_FATURAMENTO_DIARIO
	AFTER INSERT ON ITENS_NOTAS FOR EACH ROW BEGIN
    /* -- CODIGO_OMITIDO -- */
END//

DELIMITER //
CREATE TRIGGER NOME_DA_TRIGGER 
	BEFORE INSERT
	ON NOME_DA_TABELA FOR EACH ROW BEGIN
    /* -- CODIGO_OMITIDO -- */
END//

DELIMITER //
CREATE TRIGGER NOME_DA_TRIGGER
	AFTER UPDATE ON NOME_DA_TABELA FOR EACH ROW BEGIN
    /* -- CODIGO_OMITIDO -- */
END//

DELIMITER //
CREATE TRIGGER NOME_DA_TRIGGER
	AFTER DELETE ON NOME_DA_TABELA FOR EACH ROW BEGIN
    /* -- CODIGO_OMITIDO -- */
END//

/*----------------EXEMPLOS PRÁTICOS---------------------*/
DELIMITER //
CREATE TRIGGER TG_CALCULA_FATURAMENTO_DIARIO
	AFTER INSERT ON ITENS_NOTAS FOR EACH ROW BEGIN
    DELETE FROM TABELA_FATURAMENTO;
    INSERT INTO TABELA_FATURAMENTO(DATA_VENDA, TOTAL_VENDA)
    SELECT DATA_VENDA, SUM(VENDA) FROM ITENS_NOTAS GROUP BY DATA_VENDA; 
END//

/* -----------------------TESTANDO A TRIGGER DE CIMA----------------------- */
INSERT INTO ITENS_NOTAS (NUMERO, DATA_VENDA, VENDA) VALUES (1, '2019-07-16', 2300.0);
INSERT INTO ITENS_NOTAS (NUMERO, DATA_VENDA, VENDA) VALUES (2, '2019-07-16', 1700.0);
INSERT INTO ITENS_NOTAS (NUMERO, DATA_VENDA, VENDA) VALUES (3, '2019-07-16', 2500.0);
INSERT INTO ITENS_NOTAS (NUMERO, DATA_VENDA, VENDA) VALUES (4, '2019-07-17', 1200.0);
INSERT INTO ITENS_NOTAS (NUMERO, DATA_VENDA, VENDA) VALUES (5, '2019-07-16', 1.0);

SELECT * FROM TABELA_FATURAMENTO;

/*----------------SEGUNDO EXEMPLO PRÁTICOS---------------------*/
DELIMITER //
CREATE TRIGGER CALCULA_IDADE
	BEFORE INSERT ON TABELA_CLIENTES FOR EACH ROW BEGIN
	SET NEW.IDADE = TIMESTAMPDIFF(YEAR, NEW.DATA_NASCIMENTO, NOW());	/* O OPERADOR NEW SERVE REPRESENTA O NOVO REGISTRO QUE SERÁ INCLUÍDO */
END//

SELECT NOME, TIMESTAMPDIFF(YEAR, DATA_NASCIMENTO, NOW()) AS ANOS FROM CLIENTES;	/* calcula a idade do cliente automaticamente */

/* -----------------------TESTANDO A TRIGGER DE CIMA----------------------- */
INSERT INTO TABELA_CLIENTES (NOME, DATA_NASCIMENTO, IDADE) VALUES ('Anderson', '2006-07-16', 10);
INSERT INTO TABELA_CLIENTES (NOME, DATA_NASCIMENTO, IDADE) VALUES ('Maria', '1998-06-15', 16);
INSERT INTO TABELA_CLIENTES (NOME, DATA_NASCIMENTO, IDADE) VALUES ('Túlio', '1970-09-03', 5);
INSERT INTO TABELA_CLIENTES (NOME, DATA_NASCIMENTO, IDADE) VALUES ('Jorge', '1994-03-13', 17);

SELECT * FROM TABELA_CLIENTES;
