CREATE DATABASE IF NOT EXISTS vendas_suco DEFAULT CHARACTER SET utf8;

USE vendas_suco;

CREATE TABLE PRODUTOS(
	CODIGO VARCHAR(10) NOT NULL,	/* NÃO PODE SER NULL */
    DESCRITOR VARCHAR(100) NULL,	/* PODE SER NULL */
    SABOR VARCHAR(50) NULL,
    TAMANHO VARCHAR(50) NULL,
    EMBALAGEM VARCHAR(50) NULL,
    PRECO_LISTA FLOAT,
    PRIMARY KEY (CODIGO)
    );
    
CREATE TABLE VENDEDORES(
	MATRICULA VARCHAR(5) NOT NULL, 
    NOME VARCHAR(100) NULL,
    BAIRRO VARCHAR(50) NULL,
    COMISSAO FLOAT NULL,
    DATA_ADMISSAO DATE NULL,
    FÉRIAS BIT(1) NULL,
    PRIMARY KEY (MATRICULA)
);

/* RENOMEAR NOME DE COLUNAS (SE A COLUNA FOR PRIMARY KEY SERÁ MAIS DIFÍCIL) */
ALTER TABLE VENDEDORES RENAME COLUMN FÉRIAS TO FERIAS;
