/* Atualiza a idade dos clientes */

USE sucos_vendas;
DROP PROCEDURE IF EXISTS `sp_Exerc02`;

DELIMITER $$
USE `sucos_vendas`$$
CREATE PROCEDURE sp_Exerc02()
BEGIN
	SELECT IDADE FROM TABELA_DE_CLIENTES;
	UPDATE TABELA_DE_CLIENTES SET IDADE = TIMESTAMPDIFF(YEAR, DATA_DE_NASCIMENTO, CURDATE());
    SELECT IDADE FROM TABELA_DE_CLIENTES;
END $$
DELIMITER ;

SELECT * FROM tabela_de_clientes;
CALL sp_Exerc02();